import type { Student, Teacher, FeeRecord, AttendanceRecord, AdmissionLead, DashboardStats } from "@/types";

export const mockDashboardStats: DashboardStats = {
  totalStudents: 1247,
  totalTeachers: 86,
  attendanceRate: 94.3,
  feeCollectionRate: 87.5,
  newAdmissions: 43,
  pendingFees: 128,
};

export const mockStudents: Student[] = [
  {
    id: "1",
    studentId: "STU-2024-001",
    firstName: "Aarav",
    lastName: "Sharma",
    fullName: "Aarav Sharma",
    grade: "Grade 10",
    section: "A",
    status: "active",
    gender: "male",
    dateOfBirth: "2009-03-15",
    bloodGroup: "O+",
    address: "House 12, Humhama Road, Srinagar",
    phone: "+91 94191 23456",
    email: "aarav.student@school.edu",
    parentName: "Arjun Sharma",
    parentPhone: "+91 94192 76543",
    enrollmentDate: "2022-09-01",
    schoolId: "school-1",
  },
  {
    id: "2",
    studentId: "STU-2024-002",
    firstName: "Fatima",
    lastName: "Sheikh",
    fullName: "Fatima Sheikh",
    grade: "Grade 9",
    section: "B",
    status: "active",
    gender: "female",
    dateOfBirth: "2010-07-22",
    bloodGroup: "A+",
    address: "House 8, Rajbagh Colony, Srinagar",
    phone: "+91 94193 45678",
    parentName: "Vikram Kaul",
    parentPhone: "+91 94194 87654",
    enrollmentDate: "2023-09-01",
    schoolId: "school-1",
  },
  {
    id: "3",
    studentId: "STU-2024-003",
    firstName: "Aryan",
    lastName: "Koul",
    fullName: "Aryan Koul",
    grade: "Grade 11",
    section: "A",
    status: "active",
    gender: "male",
    dateOfBirth: "2008-11-10",
    bloodGroup: "B+",
    address: "House 21, Nowgam Colony, Srinagar",
    parentName: "Ranjit Koul",
    parentPhone: "+91 94195 56789",
    enrollmentDate: "2021-09-01",
    schoolId: "school-1",
  },
  {
    id: "4",
    studentId: "STU-2024-004",
    firstName: "Noor",
    lastName: "Kaul",
    fullName: "Noor Kaul",
    grade: "Grade 8",
    section: "C",
    status: "active",
    gender: "female",
    dateOfBirth: "2011-05-18",
    bloodGroup: "AB+",
    parentName: "Sunita Kaul",
    parentPhone: "+91 94196 67890",
    enrollmentDate: "2023-09-01",
    schoolId: "school-1",
  },
  {
    id: "5",
    studentId: "STU-2024-005",
    firstName: "Yusuf",
    lastName: "Mir",
    fullName: "Yusuf Mir",
    grade: "Grade 12",
    section: "B",
    status: "active",
    gender: "male",
    dateOfBirth: "2007-09-03",
    bloodGroup: "O-",
    parentName: "Ibrahim Mir",
    parentPhone: "+91 94197 78901",
    enrollmentDate: "2019-09-01",
    schoolId: "school-1",
  },
];

export const mockTeachers: Teacher[] = [
  {
    id: "1",
    employeeId: "TCH-001",
    fullName: "Dr. Priya Sharma",
    email: "priya.sharma@school.edu",
    phone: "+91 94198 11222",
    subject: "Mathematics",
    qualification: "PhD in Mathematics",
    status: "active",
    joinDate: "2019-08-15",
    schoolId: "school-1",
  },
  {
    id: "2",
    employeeId: "TCH-002",
    fullName: "Mr. Imran Khan",
    email: "imran.khan@school.edu",
    phone: "+91 94198 33444",
    subject: "Physics",
    qualification: "MSc in Physics",
    status: "active",
    joinDate: "2020-09-01",
    schoolId: "school-1",
  },
  {
    id: "3",
    employeeId: "TCH-003",
    fullName: "Ms. Neha Gupta",
    email: "neha.gupta@school.edu",
    phone: "+91 94198 55666",
    subject: "English Language",
    qualification: "MA in English Literature",
    status: "active",
    joinDate: "2021-01-15",
    schoolId: "school-1",
  },
];

export const mockFeeRecords: FeeRecord[] = [
  {
    id: "1",
    studentId: "1",
    studentName: "Aarav Sharma",
    grade: "Grade 10",
    feeType: "Tuition Fee - Semester 1",
    amount: 15000,
    paidAmount: 15000,
    dueDate: "2024-09-30",
    status: "paid",
    schoolId: "school-1",
  },
  {
    id: "2",
    studentId: "2",
    studentName: "Fatima Sheikh",
    grade: "Grade 9",
    feeType: "Tuition Fee - Semester 1",
    amount: 15000,
    paidAmount: 7500,
    dueDate: "2024-09-30",
    status: "partial",
    schoolId: "school-1",
  },
  {
    id: "3",
    studentId: "3",
    studentName: "Aryan Koul",
    grade: "Grade 11",
    feeType: "Tuition Fee - Semester 1",
    amount: 15000,
    paidAmount: 0,
    dueDate: "2024-09-30",
    status: "overdue",
    schoolId: "school-1",
  },
  {
    id: "4",
    studentId: "4",
    studentName: "Noor Kaul",
    grade: "Grade 8",
    feeType: "Tuition Fee - Semester 1",
    amount: 12000,
    paidAmount: 12000,
    dueDate: "2024-09-30",
    status: "paid",
    schoolId: "school-1",
  },
  {
    id: "5",
    studentId: "5",
    studentName: "Yusuf Mir",
    grade: "Grade 12",
    feeType: "Tuition Fee - Semester 1",
    amount: 15000,
    paidAmount: 0,
    dueDate: "2024-10-15",
    status: "pending",
    schoolId: "school-1",
  },
];

export const mockAttendance: AttendanceRecord[] = [
  { id: "1", studentId: "1", studentName: "Aarav Sharma", grade: "Grade 10", date: "2024-06-13", status: "present", schoolId: "school-1" },
  { id: "2", studentId: "2", studentName: "Fatima Sheikh", grade: "Grade 9", date: "2024-06-13", status: "present", schoolId: "school-1" },
  { id: "3", studentId: "3", studentName: "Aryan Koul", grade: "Grade 11", date: "2024-06-13", status: "absent", schoolId: "school-1" },
  { id: "4", studentId: "4", studentName: "Noor Kaul", grade: "Grade 8", date: "2024-06-13", status: "late", schoolId: "school-1" },
  { id: "5", studentId: "5", studentName: "Yusuf Mir", grade: "Grade 12", date: "2024-06-13", status: "present", schoolId: "school-1" },
];

export const mockAdmissionLeads: AdmissionLead[] = [
  {
    id: "1",
    leadId: "LEAD-2024-001",
    studentName: "Rahul Sharma",
    parentName: "Sunil Sharma",
    parentPhone: "+91 94190 99888",
    parentEmail: "sunil.sharma@email.com",
    gradeApplied: "Grade 5",
    status: "new",
    createdAt: "2024-06-10",
    schoolId: "school-1",
  },
  {
    id: "2",
    leadId: "LEAD-2024-002",
    studentName: "Lina Mehta",
    parentName: "Suresh Kumar",
    parentPhone: "+91 94190 77666",
    parentEmail: "suresh.kumar@email.com",
    gradeApplied: "Grade 7",
    status: "contacted",
    createdAt: "2024-06-08",
    schoolId: "school-1",
  },
  {
    id: "3",
    leadId: "LEAD-2024-003",
    studentName: "Rohan Gupta",
    parentName: "Deepak Gupta",
    parentPhone: "+91 94190 55444",
    parentEmail: "deepak.gupta@email.com",
    gradeApplied: "Grade 1",
    status: "interview_scheduled",
    createdAt: "2024-06-05",
    schoolId: "school-1",
  },
];
