import type { Student, Teacher, FeeRecord, AttendanceRecord, AdmissionLead, DashboardStats } from "@/types";

export const mockDashboardStats: DashboardStats = {
  totalStudents: 1247,
  totalTeachers: 86,
  attendanceRate: 94.3,
  feeCollectionRate: 87.5,
  newAdmissions: 43,
  pendingFees: 128,
};

export const mockStudents: Student[] = [
  {
    id: "1",
    studentId: "STU-2024-001",
    firstName: "Ahmed",
    lastName: "Al-Rashidi",
    fullName: "Ahmed Al-Rashidi",
    grade: "Grade 10",
    section: "A",
    status: "active",
    gender: "male",
    dateOfBirth: "2009-03-15",
    bloodGroup: "O+",
    address: "123 King Fahd Road, Riyadh",
    phone: "+966 50 123 4567",
    email: "ahmed.student@school.edu",
    parentName: "Mohammed Al-Rashidi",
    parentPhone: "+966 50 765 4321",
    enrollmentDate: "2022-09-01",
    schoolId: "school-1",
  },
  {
    id: "2",
    studentId: "STU-2024-002",
    firstName: "Fatima",
    lastName: "Al-Zahrani",
    fullName: "Fatima Al-Zahrani",
    grade: "Grade 9",
    section: "B",
    status: "active",
    gender: "female",
    dateOfBirth: "2010-07-22",
    bloodGroup: "A+",
    address: "456 Prince Sultan St, Jeddah",
    phone: "+966 55 234 5678",
    parentName: "Khalid Al-Zahrani",
    parentPhone: "+966 55 876 5432",
    enrollmentDate: "2023-09-01",
    schoolId: "school-1",
  },
  {
    id: "3",
    studentId: "STU-2024-003",
    firstName: "Omar",
    lastName: "Al-Ghamdi",
    fullName: "Omar Al-Ghamdi",
    grade: "Grade 11",
    section: "A",
    status: "active",
    gender: "male",
    dateOfBirth: "2008-11-10",
    bloodGroup: "B+",
    address: "789 Olaya St, Riyadh",
    parentName: "Abdullah Al-Ghamdi",
    parentPhone: "+966 56 345 6789",
    enrollmentDate: "2021-09-01",
    schoolId: "school-1",
  },
  {
    id: "4",
    studentId: "STU-2024-004",
    firstName: "Nora",
    lastName: "Al-Otaibi",
    fullName: "Nora Al-Otaibi",
    grade: "Grade 8",
    section: "C",
    status: "active",
    gender: "female",
    dateOfBirth: "2011-05-18",
    bloodGroup: "AB+",
    parentName: "Saleh Al-Otaibi",
    parentPhone: "+966 50 456 7890",
    enrollmentDate: "2023-09-01",
    schoolId: "school-1",
  },
  {
    id: "5",
    studentId: "STU-2024-005",
    firstName: "Yusuf",
    lastName: "Al-Dosari",
    fullName: "Yusuf Al-Dosari",
    grade: "Grade 12",
    section: "B",
    status: "active",
    gender: "male",
    dateOfBirth: "2007-09-03",
    bloodGroup: "O-",
    parentName: "Ibrahim Al-Dosari",
    parentPhone: "+966 54 567 8901",
    enrollmentDate: "2019-09-01",
    schoolId: "school-1",
  },
];

export const mockTeachers: Teacher[] = [
  {
    id: "1",
    employeeId: "TCH-001",
    fullName: "Dr. Sarah Al-Hamdan",
    email: "sarah.hamdan@school.edu",
    phone: "+966 50 111 2222",
    subject: "Mathematics",
    qualification: "PhD in Mathematics",
    status: "active",
    joinDate: "2019-08-15",
    schoolId: "school-1",
  },
  {
    id: "2",
    employeeId: "TCH-002",
    fullName: "Mr. Khalid Al-Mutairi",
    email: "khalid.mutairi@school.edu",
    phone: "+966 55 333 4444",
    subject: "Physics",
    qualification: "MSc in Physics",
    status: "active",
    joinDate: "2020-09-01",
    schoolId: "school-1",
  },
  {
    id: "3",
    employeeId: "TCH-003",
    fullName: "Ms. Reem Al-Harbi",
    email: "reem.harbi@school.edu",
    phone: "+966 56 555 6666",
    subject: "English Language",
    qualification: "BA in English Literature",
    status: "active",
    joinDate: "2021-01-15",
    schoolId: "school-1",
  },
];

export const mockFeeRecords: FeeRecord[] = [
  {
    id: "1",
    studentId: "1",
    studentName: "Ahmed Al-Rashidi",
    grade: "Grade 10",
    feeType: "Tuition Fee - Semester 1",
    amount: 15000,
    paidAmount: 15000,
    dueDate: "2024-09-30",
    status: "paid",
    schoolId: "school-1",
  },
  {
    id: "2",
    studentId: "2",
    studentName: "Fatima Al-Zahrani",
    grade: "Grade 9",
    feeType: "Tuition Fee - Semester 1",
    amount: 15000,
    paidAmount: 7500,
    dueDate: "2024-09-30",
    status: "partial",
    schoolId: "school-1",
  },
  {
    id: "3",
    studentId: "3",
    studentName: "Omar Al-Ghamdi",
    grade: "Grade 11",
    feeType: "Tuition Fee - Semester 1",
    amount: 15000,
    paidAmount: 0,
    dueDate: "2024-09-30",
    status: "overdue",
    schoolId: "school-1",
  },
  {
    id: "4",
    studentId: "4",
    studentName: "Nora Al-Otaibi",
    grade: "Grade 8",
    feeType: "Tuition Fee - Semester 1",
    amount: 12000,
    paidAmount: 12000,
    dueDate: "2024-09-30",
    status: "paid",
    schoolId: "school-1",
  },
  {
    id: "5",
    studentId: "5",
    studentName: "Yusuf Al-Dosari",
    grade: "Grade 12",
    feeType: "Tuition Fee - Semester 1",
    amount: 15000,
    paidAmount: 0,
    dueDate: "2024-10-15",
    status: "pending",
    schoolId: "school-1",
  },
];

export const mockAttendance: AttendanceRecord[] = [
  { id: "1", studentId: "1", studentName: "Ahmed Al-Rashidi", grade: "Grade 10", date: "2024-06-13", status: "present", schoolId: "school-1" },
  { id: "2", studentId: "2", studentName: "Fatima Al-Zahrani", grade: "Grade 9", date: "2024-06-13", status: "present", schoolId: "school-1" },
  { id: "3", studentId: "3", studentName: "Omar Al-Ghamdi", grade: "Grade 11", date: "2024-06-13", status: "absent", schoolId: "school-1" },
  { id: "4", studentId: "4", studentName: "Nora Al-Otaibi", grade: "Grade 8", date: "2024-06-13", status: "late", schoolId: "school-1" },
  { id: "5", studentId: "5", studentName: "Yusuf Al-Dosari", grade: "Grade 12", date: "2024-06-13", status: "present", schoolId: "school-1" },
];

export const mockAdmissionLeads: AdmissionLead[] = [
  {
    id: "1",
    leadId: "LEAD-2024-001",
    studentName: "Hassan Al-Qahtani",
    parentName: "Faisal Al-Qahtani",
    parentPhone: "+966 50 999 8888",
    parentEmail: "faisal@email.com",
    gradeApplied: "Grade 5",
    status: "new",
    createdAt: "2024-06-10",
    schoolId: "school-1",
  },
  {
    id: "2",
    leadId: "LEAD-2024-002",
    studentName: "Lina Al-Shamri",
    parentName: "Saad Al-Shamri",
    parentPhone: "+966 55 777 6666",
    parentEmail: "saad@email.com",
    gradeApplied: "Grade 7",
    status: "contacted",
    createdAt: "2024-06-08",
    schoolId: "school-1",
  },
  {
    id: "3",
    leadId: "LEAD-2024-003",
    studentName: "Rayan Al-Barrak",
    parentName: "Turki Al-Barrak",
    parentPhone: "+966 56 555 4444",
    parentEmail: "turki@email.com",
    gradeApplied: "Grade 1",
    status: "interview_scheduled",
    createdAt: "2024-06-05",
    schoolId: "school-1",
  },
];
